### ISSUE TITLE
Example not working with Jar input

### ISSUE THREAD

**Issue by akshayutture** [ucla-pls/jreduce#1]
The example from the 'example' folder, which is used in the Readme example, runs as expected when the input is a folder of class-files.
However, when given a jar file as input, it does not perform any reduction.

**Comment by kalhauge** [comment]
Hi, can you try again with this new version?

**Comment by akshayutture** [comment]
Yes. It seems like the new version fixes this issue.

**Comment by kalhauge** [comment]
Fantastic!
