### ISSUE TITLE
Option to supress warnings about missing classes needed

### ISSUE THREAD

**Issue by akshayutture** [ucla-pls/jreduce#10]
Jreduce seems to be printing more warnings since the last commit that fixed Issue#6 . Is there an option to avoid printing the warnings?

**Here is the jar file**
https://drive.google.com/file/d/1Wk9Pd6PKBLprXh3N0KLPI6TUSwoyaMGs/view?usp=sharing

**Here are the logs. The extra warnings are in bold**
+ jreduce --work-folder _jreduce/workfolder --jre /usr/lib/jvm/java-8-openjdk-amd64/jre -S items+logic --stdlib ../../stdlib.bin -o app+lib.after.jar --predicate-timelimit 180 app+lib.jar -- ls
16:48:27 ├ JReduce
16:48:27 │ ├ Started JReduce.
16:48:27 │ ├ Reading inputs
16:48:27 │ │ └ 0.003s
16:48:27 │ ├ Calculating Initial Problem
16:48:27 │ │ ├ setup
16:48:27 │ │ │ └ 0.083s
16:48:27 │ │ ├ run
16:48:27 │ │ │ └ 0.009s
16:48:27 │ │ └ 0.093s
16:48:27 │ ├ Refining Problem
16:48:27 │ │ └ 0.230s
16:48:27 │ ├ Initializing key function
16:48:27 │ │ ├ Calculating the hierarchy
16:48:27 │ │ │ ├ Load stdlib stubs
16:48:33 │ │ │ │ └ 6.108s
16:48:33 │ │ │ ├ Load project stubs
16:48:44 │ │ │ │ └ 10.335s
16:48:44 │ │ │ ├ Compute hierarchy
16:48:46 │ │ │ │ ├ Could not find: org/apache/tools/ant/Task
16:48:46 │ │ │ │ ├ Could not find: javax/servlet/ServletContextListener
16:48:46 │ │ │ │ ├ Could not find: javax/transaction/UserTransaction
16:48:46 │ │ │ │ ├ Could not find: javax/transaction/Synchronization
16:48:46 │ │ │ │ ├ Could not find: org/apache/lucene/index/IndexDeletionPolicy
16:48:46 │ │ │ │ └ 2.607s
16:48:46 │ │ │ └ 19.051s
16:48:46 │ │ ├ Found 85238 items.
16:48:47 │ │ ├ Found 85196 facts.
16:48:47 │ │ ├ The core is 0 of them.
16:48:47 │ │ └ 20.084s
16:48:47 │ ├ Compute CNF
**16:48:48 │ │ ├ Warnings found while computing logical dependencies for com/avaje/ebean/config/PropertyMapLoader.findInputStream:(Ljava/lang/String;)Ljava/io/InputStream;!code
16:48:48 │ │ ├ Could not find "javax/servlet/ServletContext.getResourceAsStream:(Ljava/lang/String;)Ljava/io/InputStream;"
16:48:48 │ │ ├ Warnings found while computing logical dependencies for com/avaje/ebean/config/lucene/AbstractIndexDefn.getMaxFieldLength:()Lorg/apache/lucene/index/IndexWriter$MaxFieldLength;!code
16:48:48 │ │ ├ Could not find "org/apache/lucene/index/IndexWriter$MaxFieldLength.UNLIMITED:Lorg/apache/lucene/index/IndexWriter$MaxFieldLength;"**
jreduce: "com/avaje/ebean/enhance/ant/AntEnhanceTask.<init>:()V" Just (ByteCodeInst {offset = 1, opcode = Invoke (InvkSpecial (AbsVariableMethodId {variableIsInterface = False, variableMethodId = InRefType {inRefType = "Lorg/apache/tools/ant/Task;", inRefTypeId = "<init>:()V"}}))}) NotSubtype (TRef ["Lcom/avaje/ebean/enhance/ant/AntEnhanceTask;"]) (TRef ["Lorg/apache/tools/ant/Task;"])
CallStack (from HasCallStack):
  error, called at src/JReduce/Logic.hs:990:31 in jreduce-0.1.0-Abs4ufFiDadAKpDliDdD1j:JReduce.Logic
CallStack (from -prof):
  JReduce.Logic.logic.typeCheckStates (src/JReduce/Logic.hs:(988,7)-(996,29))
  JReduce.Logic.logic (src/JReduce/Logic.hs:(643,1)-(1033,35))
  JReduce.Logic.initializeKeyFunction (src/JReduce/Logic.hs:(278,1)-(384,69))
  JReduce.Logic.computeCNF (src/JReduce/Logic.hs:(393,1)-(400,12))
  JReduce.Logic.describeLogicProblem.\ (src/JReduce/Logic.hs:(492,91)-(575,5))
  Control.Reduce.Problem.refineProblemA' (src/Control/Reduce/Problem.hs:(495,1)-(503,5))
  JReduce.Logic.describeLogicProblem (src/JReduce/Logic.hs:(492,1)-(575,5))
  JReduce.run.\ (src/JReduce.hs:(101,52)-(193,44))
  Control.Reduce.Util.OptParse.withWorkFolder (src/Control/Reduce/Util/OptParse.hs:(96,1)-(105,41))
  JReduce.run (src/JReduce.hs:(96,1)-(224,40))
  Control.Reduce.Util.Logger.timeIO (src/Control/Reduce/Util/Logger.hs:(249,1)-(253,48))
  Control.Reduce.Util.Logger.timedPhase'.runMa (src/Control/Reduce/Util/Logger.hs:163:7-84)
  Control.Reduce.Util.Logger.timedPhase' (src/Control/Reduce/Util/Logger.hs:(161,1)-(181,11))
  JReduce.main (src/JReduce.hs:(69,1)-(81,48))

**Comment by kalhauge** [comment]
Is it important to suppress the warnings? You can use the `-q` option to make the evaluation print less. Is this enough?

**Comment by akshayutture** [comment]
I guess that should be enough.

**Comment by akshayutture** [comment]
Actually, it still is printing some warnings messages. But it's just 3 benchmarks. So I think it's fine. We can skip it.
