### ISSUE TITLE
Jreduce stuck at some iteration because the predicate gets stuck

### ISSUE THREAD

**Issue by akshayutture** [ucla-pls/jreduce#5]
On a benchmark (number 05 from https://github.com/jdebloat/jdebloat), the predicate (which is the test-suite passing successfully) gets stuck (i.e. doesn't terminate in 24 hours) at iteration 457.
A similar thing happens to another benchmark (number 02) at a different iteration number.

Here is the command used
./jdebloat.py run jreduce --csv benchmarks --benchmark 05

There is no error when it is run with the '-S classes' option.

What details shall I provide you so that you may reproduce it?

**Comment by kalhauge** [comment]
It sounds like you have a flaky predicate. Those are hard to manage.

Jreduce is built with a '--timelimit' which should kill the predicate after some time. For example setting it to 1800s ~ 0.5 h should preempt the run early. If that does not work, it's a bug that we should fix.

As a alternative solution, you can build in a time limit into your predicate. 
If it is a bash script you can use the  `timeout` program, or by using one of the tricks from https://mywiki.wooledge.org/BashFAQ/068

**Comment by akshayutture** [comment]
1) Jreduce was running with the (--timelimit 1800) option, but it did not pre-empt the run early.

2) I also tried building a 1800s timeout into the predicate. Iterations number 457 and 458 correctly timed out after 1800s each, but the whole script seems to have terminated in the middle of iteration 459, and Jreduce produced no output.

So in this case, Jreduce was running with the (--timelimit 1800) option and should have terminated after 457, since a total of 1800s were already up after it was done. Maybe it is not counting the time taken by the predicate in its 1800s estimate?

**Comment by kalhauge** [comment]
Turns out the timelimit option is broken and the `--predicate-timelimit` should be used instead. I have removed the other option completly so a error is thrown early.
