### ISSUE TITLE
Missing Class Enhancement 

### ISSUE THREAD

**Issue by akshayutture** [ucla-pls/jreduce#9]
Issue #4 was supposed to add an enhancement to work with missing classes. However Jreduce still crashes when given a jar file with missing classes. There seems to be no change in the output. Is there a certain option that needs to be set to work with missing classes?

**Here is the Jar file**
https://drive.google.com/file/d/1NX-g9GqBsIf_fNGwEu3V7qZiyiqs22vk/view?usp=sharing

**Here is the log**
+ jreduce --work-folder _jreduce/workfolder --jre /usr/lib/jvm/java-8-openjdk-amd64/jre -S items+logic --core @jreduce_core.txt --stdlib ../../stdlib.bin -o app+lib.after.jar --predicate-timelimit 180 app+lib.jar -- timeout 180 /home/akshayutture/projects/jdebloat/scripts/predicate.sh /home/akshayutture/projects/jdebloat/output/15/initial+jreduce '{}'
10:53:53 ├ JReduce
10:53:53 │ ├ Started JReduce.
10:53:53 │ ├ Reading inputs
10:53:53 │ │ └ 0.003s
10:53:53 │ ├ Calculating Initial Problem
10:53:53 │ │ ├ setup
10:54:05 │ │ │ └ 12.215s
10:54:05 │ │ ├ run
10:54:09 │ │ │ └ 4.030s
10:54:09 │ │ └ 16.258s
10:54:09 │ ├ Refining Problem
10:54:09 │ │ └ 0.163s
10:54:09 │ ├ Initializing key function
10:54:09 │ │ ├ Calculating the hierarchy
10:54:09 │ │ │ ├ Load stdlib stubs
10:54:16 │ │ │ │ └ 6.704s
10:54:16 │ │ │ ├ Load project stubs
10:54:26 │ │ │ │ └ 9.588s
10:54:27 │ │ │ ├ Compute hierarchy
10:54:30 │ │ │ │ ├ Could not find: net/sf/cglib/proxy/MethodInterceptor
10:54:30 │ │ │ │ ├ Could not find: net/sf/cglib/proxy/MethodInterceptor
10:54:30 │ │ │ │ └ 2.889s
10:54:30 │ │ │ └ 20.995s
10:54:30 │ │ ├ Found 70536 items.
10:54:31 │ │ ├ Found 70520 facts.
10:54:31 │ │ ├ The core is 13952 of them.
10:54:31 │ │ └ 21.906s
10:54:31 │ ├ Compute CNF
jreduce: "org/apache/ibatis/executor/loader/cglib/CglibProxyFactory$EnhancedDeserializationProxyImpl.createProxy:(Ljava/lang/Object;Ljava/util/Map;Lorg/apache/ibatis/reflection/factory/ObjectFactory;Ljava/util/List;Ljava/util/List;)Ljava/lang/Object;" Just (ByteCodeInst {offset = 29, opcode = Invoke (InvkStatic (AbsVariableMethodId {variableIsInterface = False, variableMethodId = InRefType {inRefType = "Lorg/apache/ibatis/executor/loader/cglib/CglibProxyFactory;", inRefTypeId = "crateProxy:(Ljava/lang/Class;Lnet/sf/cglib/proxy/Callback;Ljava/util/List;Ljava/util/List;)Ljava/lang/Object;"}}))}) NotSubtype (TRef ["Lorg/apache/ibatis/executor/loader/cglib/CglibProxyFactory$EnhancedDeserializationProxyImpl;"]) (TRef ["Lnet/sf/cglib/proxy/Callback;"])
CallStack (from HasCallStack):
  error, called at src/JReduce/Logic.hs:990:31 in jreduce-0.1.0-Abs4ufFiDadAKpDliDdD1j:JReduce.Logic
CallStack (from -prof):
  JReduce.Logic.logic.typeCheckStates (src/JReduce/Logic.hs:(988,7)-(996,29))
  JReduce.Logic.logic (src/JReduce/Logic.hs:(643,1)-(1033,35))
  JReduce.Logic.initializeKeyFunction (src/JReduce/Logic.hs:(278,1)-(384,69))
  JReduce.Logic.computeCNF (src/JReduce/Logic.hs:(393,1)-(400,12))
  JReduce.Logic.describeLogicProblem.\ (src/JReduce/Logic.hs:(492,91)-(575,5))
  Control.Reduce.Problem.refineProblemA' (src/Control/Reduce/Problem.hs:(495,1)-(503,5))
  JReduce.Logic.describeLogicProblem (src/JReduce/Logic.hs:(492,1)-(575,5))
  JReduce.run.\ (src/JReduce.hs:(101,52)-(193,44))
  Control.Reduce.Util.OptParse.withWorkFolder (src/Control/Reduce/Util/OptParse.hs:(96,1)-(105,41))
  JReduce.run (src/JReduce.hs:(96,1)-(224,40))
  Control.Reduce.Util.Logger.timeIO (src/Control/Reduce/Util/Logger.hs:(249,1)-(253,48))
  Control.Reduce.Util.Logger.timedPhase'.runMa (src/Control/Reduce/Util/Logger.hs:163:7-84)
  Control.Reduce.Util.Logger.timedPhase' (src/Control/Reduce/Util/Logger.hs:(161,1)-(181,11))
  JReduce.main (src/JReduce.hs:(69,1)-(81,48))

**Comment by kalhauge** [comment]
This seems like a typechecking error. Is this related to #8?

**Comment by kalhauge** [comment]
I have added an `--unsafe` option that allows you to ignore these warnings. It might be a temporary workaround.

**Comment by akshayutture** [comment]
Yes. This fixes 5/9 benchmarks completely. That is great! Now once we have deal with issue #10 we should be all good to go.
